### ISSUE TITLE
New nightly board interface

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/nightly-board#22]
First batch of the rework of the https://nightly.prestashop.com/ platform :
- add new features
- improve design

Other improvements should be done in a future batch

**Comment by colinegin** [comment]
ping @SimonGrn and @prestascott if you want to add details and link to mockups so that we can have a history on the work that has been done (and the why ;) )

**Comment by SimonGrn** [comment]
It was pushed to production this morning. How do you want us to track the advancement ?

**Comment by colinegin** [comment]
it was just to have a card in the side project kanban with a definition of what has been done

**Comment by SimonGrn** [comment]
Updated today: new design, new architecture (REST JSON API + Vue App).
