### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/nightly-board#26]
- new `DELETE` route to delete a report (protected with an `Authentication` header containing the token value)
- adding a more REST way to insert report (`/reports` POST route, `Authentication` header with token value, JSON data in payload)
- percentage bar for every suite to visualize how a test suite performed
- adding a *browser* and a *campaign* information on the homepage
- adding a *browser* and a *campaign* filter on the homepage
- adding variability in homepage (discrepancy between current run and precedent run)
- adding the file path on toggled suite
- formatting failed tests: the main error message is always visible, the stack trace is visible when toggling 
- removing overflow for desktop view
- improving mobile view (removing blank spaces)

**Comment by LouiseBonnard** [comment]
Hi @SimonGrn, what's the status of this ticket? Should I move it to the backlog in the side projects' kanban?

**Comment by SimonGrn** [comment]
This ticket is almost fully done (I just didn't create the POST route for the 2nd bullet point). Currently I'm the only developer working on it so I don't think it's that important to keep it in the Kanban.
I'm gonna close it, thanks for reminding me !
