### ISSUE TITLE
[Mobile][View report page] Desktop view display after opening a failed step

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/nightly-board#29]
**How to reproduce**

-  Open a tests report (with fails)
- Click on a failed test suite
- Scroll down
- Open a failed test step
- Scroll up

=> See error, Desktop view is displayed
![image](https://user-images.githubusercontent.com/48441421/80072382-74ae3400-8546-11ea-9749-7c7c84173948.png)

**Comment by NeOMakinG** [comment]
Should be ok now, feel free to open it again if it's not fixed
